#!/bin/bash

#$ -cwd
#$ -o stdout_exonerate_single_10096_21_jan.txt
#$ -e stderr_exonerate_single_10096_21_jan.txt
#$ -j y
#$ -S /bin/bash

wait
echo "Starting exonerate run at:"
date
wait

exonerate --query ../../Both_sets_1.fasta --query ../../Both_sets_2.fasta --target contig_10096.fasta -m cdna2genome --showtargetgff yes --ryo ">%qi length=%ql alnlen=%qal\n>%ti length=%tl alnlen=%tal\n" > contig_10096_exonerate.output

wait

echo "Done at:"
date
